### ISSUE TITLE
Frontend usage with Vite?

### ISSUE THREAD

**Issue by KonradHoeffner** [quadstorejs/quadstore#141]
Is it possible to use node-quadstore in the frontend with Vite instead of webpack?
I tried to adapt https://github.com/beautifulinteractions/node-quadstore-webpack-bundle to [Vite](https://vitejs.dev) in the following way:

```js
import leveljs from "level-js";
import { newEngine } from "quadstore-comunica";
import { Quadstore } from "quadstore";
import { DataFactory } from "rdf-data-factory";

const dataFactory = new DataFactory();

const store = new Quadstore({
	dataFactory,
	backend: leveljs("quadstore"),
	comunica: newEngine(),
});
```

But it throws the following error:

```js
Uncaught ReferenceError: global is not defined
    ta2str deserialize.js:5
    js deserialize.js:10
    __require2 chunk-FPJRMZPJ.js:14
    js iterator.js:6
    __require2 chunk-FPJRMZPJ.js:14
    js index.js:10
    __require2 chunk-FPJRMZPJ.js:14
    <anonymous> level-js:1
```

Even prepending this polyfill doesnt help:

```js
if (typeof (window as any).global === "undefined") {
	(window as any).global = window;
}
```

When I reorder the import statements and add leveljs to the end of them, I get the following error instead:

```js
Uncaught ReferenceError: Buffer is not defined
    js quadstore.js:13
    __require2 chunk-FPJRMZPJ.js:14
    js index.js:15
    __require2 chunk-FPJRMZPJ.js:14
    <anonymous> quadstore:1

```

**Comment by jacoscaz** [comment]
@KonradHoeffner seems like you're getting there! This should be fixable by making Vite fallback to something like https://www.npmjs.com/package/@marshallswain/events for the `events` module.

**Comment by KonradHoeffner** [comment]
Next error:

```
Uncaught ReferenceError: exports is not defined
    <anonymous> http://localhost:3000/node_modules/quadstore/dist/index.js?v=db8b2a82:12
index.js:12:1
    <anonymous> http://localhost:3000/node_modules/quadstore/dist/index.js?v=db8b2a82:12
    InnerModuleEvaluation self-hosted:2371
    InnerModuleEvaluation self-hosted:2371
    evaluation self-hosted:2332
```

**Comment by jacoscaz** [comment]
@KonradHoeffner any progress on using quadstore with Vite?

**Comment by KonradHoeffner** [comment]
Great advice, thanks! The following doesn't report any errors, I will import and query data and report back if there are any problems with that.

```
<script src="https://cdn.jsdelivr.net/gh/beautifulinteractions/node-quadstore-webpack-bundle/quadstore.bundle.js"></script>
...
const { leveljs, Quadstore, DataFactory, newEngine } = quadstore;

const dataFactory = new DataFactory();

const store = new Quadstore({
	dataFactory,
	backend: leveljs("quadstore"),
	comunica: newEngine(),
});
```

**Comment by jacoscaz** [comment]
That's good! As for the queries, I would suggest starting with using the `memdown` backend rather than `level-js` and see where that takes you. `level-js` uses IndexedDB, which in my experience can be incredibly slow at times. 

Other than that, depending on the number of quads and the kinds of queries you are running, you might be stumbling into https://github.com/beautifulinteractions/node-quadstore/issues/115 .

Simple matching queries should be fine, though.
