### ISSUE TITLE
Upgrade to level packages v2.x

### ISSUE THREAD

**Issue by jacoscaz** [quadstorejs/quadstore#168]
@vweevers is working on version 2 of [Level](https://github.com/Level) packages, bringing in significant changes including dropping callbacks in favor of promises. [`abstract-level`](https://github.com/Level/abstract-level) v2.0.0 is already on NPM and the [Upgrade guide](https://github.com/Level/abstract-level/blob/main/UPGRADING.md#upgrade-guide) now details the changes between v1.x and v2.x. 

Before upgrading we need to wait for the following packages to be updated to `abstract-level` v2:

- [`classic-level`](https://github.com/Level/classic-level) _[REQUIRED]_
    - ~work towards v2 happening in https://github.com/Level/classic-level/tree/v2~
    - v2.0.0 is now [on NPM](https://www.npmjs.com/package/classic-level?activeTab=versions)! Also see the [v2.0.0 commit](https://github.com/Level/classic-level/commit/26e8c7f456d418ee0ce854013c3a074268065c97) on Github.
- [`memory-level`](https://github.com/Level/memory-level) _[REQUIRED]_
    - ~no branch for v2 yet~
    - v2.0.0 is now [on NPM](https://www.npmjs.com/package/memory-level?activeTab=versions)! Also see the [v2.0.0 commit](https://github.com/Level/memory-level/commit/dff10fa8624e21a39dfcad31cefa2735cffc1746) on Github.
- [`browser-level`](https://github.com/Level/browser-level) _[REQUIRED]_
    - no branch for v2 yet 
    - discussed in https://github.com/Level/browser-level/issues/14
    - tentative deadline: December 2024
- [`@nxtedition/rocksdb`](https://github.com/ronag/rocksdb) _[OPTIONAL, not blocking]_
    - no branch for v2 yet
    - should ask @ronag an whether they intend to align with `abstract-level` v2

We should also study the potential performance impacts of moving to promise-based iteration techniques, which I suspect might make for a slightly different tradeoff between performance (slower) and maintainability (greater).

**Comment by andrefs** [comment]
While this update is not done, maybe the documentation should warn users that they shouldn't use the v2 *-level libraries?

quadstore was failing without any error messaging and it took me a while to figure that the problem was the v2 memory-level and classic-level

**Comment by jacoscaz** [comment]
Hello @andrefs!


You are absolutely right, the documentation should warn against this. Particularly given that I am not planning on updating until browser-level will also be ported to abstract-level v2.

If you can spare the time I’d appreciate a PR, otherwise I’ll take care of this myself in the next few days. 

More worrying, however, is your experience of quadstore failing *silently*. That should never happen! I guess it might be because a promise is being returned and ignored while the provided callback is never actually getting called. 

On top of mentioning this in the docs I’d like to find a way to programmatically detect this and throw, so that even if someone misses the mention they still see an error pointing them to problem. 

Will think about this in the coming days. Thank you so much for reporting this!

**Comment by jacoscaz** [comment]
@andrefs I've addressed both in https://github.com/quadstorejs/quadstore/commit/3d75789cdc763623df6d8218af9553b00a6ae1fc and https://github.com/quadstorejs/quadstore/commit/1dfe2fe9f50cf16340fa85e0b6c8954c9419fd7f , released to NPM in `quadstore@13.2.4`. Thanks again for raising! I'll hide these comments to keep this thread tidy as I'm now referencing it within the error thrown when abstract-level 2.x is detected.

**Comment by andrefs** [comment]
@jacoscaz Awesome, thanks for the quick fix!

Maybe this is overkill but if you want I think you can also add the *-level 1.x versions to the `package.json` `peerDependencies` property. I think this makes npm warn if people install later versions in parallel with `quadstore`? not sure though

Anyway, great work!

**Comment by andrefs** [comment]
Ah, I was not aware of that, then I agree :+1:
